### ISSUE TITLE
JPG image looks bad

### ISSUE THREAD

**Issue by lhao0301** [BboyHanat/TextGenerator#9]
Saving image as PNG looks better and sharper, especially the region around text because of the better encoding of png. PNG format as default is recommended.

JPG:
![image](https://user-images.githubusercontent.com/10356897/97960885-347d1780-1ded-11eb-9761-de73d22d38e0.png)

PNG:
![image](https://user-images.githubusercontent.com/10356897/97960894-38a93500-1ded-11eb-923c-c47ca746eeb5.png)

**Comment by BboyHanat** [comment]
Thanks for your comment, I will check that.

**Comment by BboyHanat** [comment]
This issue has been fixed
